version: '3'
services:
  php-service:
    build: .
    ports:
      - 80:80
    environment:
      DB_HOST: postgres-dev
      DB_NAME: testdb
      DB_USER: testdb
      DB_PASS: ae9aGhi2ahlie6aeBos9ii8taex0ieChooQue1oqueith5eiyoo8quahtei7aideaviz4zuy0aesah6aboo0uRaingou2Oe7phah
      SSLMODE: disable
      # User foo - password bar
      # User wibble - password baz
      # remember $$ means a literal $
      HTPASSWD_FILE: |
        foo:$$apr1$$3wYuLEgT$$e3kDOxsdSy4WAMve/EFW//
        wibble:$$apr1$$TN46Uqtv$$iUmCCp0RaoZ9KZjJy5mNt0
    depends_on:
      - postgres-dev
      - nginx-reverse-proxy
    volumes:
      - ./src/:/var/www/html/
    networks:
      app_net:
        ipv4_address: 10.100.0.2

  postgres-dev:
    image: postgres:9.6.11
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=ae9aGhi2ahlie6aeBos9ii8taex0ieChooQue1oqueith5eiyoo8quahtei7aideaviz4zuy0aesah6aboo0uRaingou2Oe7phah
    volumes:
      - postgres-dev:/var/lib/postgresql/data
      - ./db-seeds/:/docker-entrypoint-initdb.d
    networks:
      app_net:
        ipv4_address: 10.100.0.3

  nginx-reverse-proxy:
    image: nginx:1-alpine
    ports:
      - 443:443
    volumes:
      - nginx-ssl:/etc/ssl/self-signed-certs/
      - ./nginx-config/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-config/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      app_net:
        ipv4_address: 10.100.0.4

volumes:
  postgres-dev:
    driver: local
  nginx-ssl:
    driver: local

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
